### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by 13hakta** [pieterb/webdav-php#5]
Please provide examples of usage of your package.

**Comment by niekbosch** [comment]
The library can be used by:

 * subclassing DAV_Resource (or DAVACL_Resource if you want to use ACL's)
 * subclassing DAV_Registry and assign an instance of your subclass to DAV::$REGISTRY
 * subclassing DAV_Lock_Provider and assign an instance of your subclass to DAV::$LOCKPROVIDER
 * if you want to use ACL's: subclassing DAVACL_ACL_Provider and assign an instance of your subclass to DAV::$ACLPROVIDER

Then, configure Apache to redirect all requests (to non-existing files) to index.php and after bootstrapping your application, run:

```php
$request = DAV_Request::inst();
if ( $request ) {
    $request->handleRequest();
}
```

This library was originally part of the code for BeeHub. It is still primarilly maintained for that use case. This means BeeHub is a the best example of how this code can be used:

https://github.com/sara-nl/BeeHub
